name: smt-jit Docker Release Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Init
      uses: actions/checkout@v1
      with:
        submodules: true
        ref: ${{ github.ref }}
      outputs:
        start_date: ${{ $(date +%s) }}
        image_tag: ${{ format('smt-jit-ci-release:{0}', start_date }} 
    - name: Build
      run: docker build . --file jit/docker/build-smt-jit.Dockerfile
           --build-arg CONFIG=debug --build-arg BUILD_TYPE=release
           --tag ${{ steps.Init.outputs.image_tag }}
    - name: RunTests
      run: docker run -it ${{ steps.Init.outputs.image_tag }} /bin/date

