name: smt-jit Docker Release Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: true
        ref: ${{ github.ref }}
    - name: Build Docker
      run: docker build . --file jit/docker/build-smt-jit.Dockerfile
           --build-arg CONFIG=debug --build-arg BUILD_TYPE=release
           --tag build-smt-jit:release
    - name: RunTests
      run: docker run -it build-smt-jit:release /bin/date

